# Generated by Django 6.0.2 on 2026-06-10 22:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('city_slug', models.SlugField(max_length=100)),
                ('service', models.CharField(choices=[('pompy', 'Pompy Ciepła'), ('klimatyzacja', 'Klimatyzacja'), ('rekuperacja', 'Rekuperacja'), ('fotowoltaika', 'Fotowoltaika')], max_length=50)),
                ('description', models.TextField()),
                ('device_model', models.CharField(blank=True, max_length=255)),
                ('area_m2', models.IntegerField(blank=True, null=True)),
                ('cover_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Realizacja',
                'verbose_name_plural': 'Realizacje',
                'ordering': ['-created_at'],
            },
        ),
    ]
