# Generated by Django 6.0.2 on 2026-06-09 20:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('service', models.CharField(choices=[('pompy', 'Pompy Ciepła'), ('klimatyzacja', 'Klimatyzacja'), ('rekuperacja', 'Rekuperacja'), ('fotowoltaika', 'Fotowoltaika'), ('o-nas', 'Dlaczego my')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zdjęcie galerii',
                'verbose_name_plural': 'Zdjęcia galerii',
                'ordering': ['service', 'order'],
            },
        ),
    ]
