# Generated by Django 6.0.2 on 2026-02-18 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Phone format: +99999999. Up to 15 digits.', regex='^\\+?[\\d\\s().-]{5,25}$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('services', models.CharField(choices=[('pompy', 'Pompy'), ('klimatyacja', 'Klimatyzacja'), ('rekuperacja', 'Rekuperacja'), ('fotowoltaika', 'Fotowoltaika'), ('serwis', 'Serwis')], default='pompy', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
