# Generated by Django 6.0.2 on 2026-02-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-createdAt']},
        ),
    ]
