# Generated by Django 6.0.2 on 2026-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='services',
            field=models.CharField(choices=[('pompy', 'Pompy'), ('klimatyzacja', 'Klimatyzacja'), ('rekuperacja', 'Rekuperacja'), ('fotowoltaika', 'Fotowoltaika'), ('serwis', 'Serwis')], default='pompy', max_length=50),
        ),
    ]
