# Generated by Django 6.0.2 on 2026-02-24 22:15

import contact.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='services',
            field=models.CharField(choices=[('pompy', 'Pompy Ciepła'), ('klimatyzacja', 'Klimatyzacja'), ('rekuperacja', 'Rekuperacja'), ('fotowoltaika', 'Fotowoltaika'), ('serwis', 'Serwis')], default='pompy', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(default=contact.models.get_default_contact_status_id, on_delete=django.db.models.deletion.PROTECT, to='contact.contactstatus'),
        ),
    ]
